apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: shipping-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8600"
spec:
  selector:
    app: shipping-service 
  ports:
    - protocol: TCP
      port: 8600 
      targetPort: 8600 
  type: ClusterIP 