apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    app: zipkin
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "9411"
spec:
  type: NodePort
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30941  # Puedes elegir un puerto entre 30000-32767
      protocol: TCP
      name: http
  selector:
    app: zipkin
