apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: ecommerce-app
  labels:
    app: zipkin
spec:
  type: NodePort
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 30941  # Puedes elegir un puerto entre 30000-32767
      protocol: TCP
      name: http
  selector:
    app: zipkin
