apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  labels:
    app: cloud-config
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "9296"
spec:
  selector:
    app: cloud-config
  ports:
    - port: 9296
      targetPort: 9296
  type: ClusterIP 