# Grafana Configuration for Ecommerce Microservices Dashboard
# Compatible with GKE and Jenkins CI/CD

# Simple admin configuration
adminUser: admin
adminPassword: admin123

# Resource configuration
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Persistent storage
persistence:
  enabled: true
  size: 10Gi
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce

# Service configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

# Environment variables
env:
  GF_USERS_ALLOW_SIGN_UP: "false"
  GF_SECURITY_ALLOW_EMBEDDING: "true"
  GF_AUTH_ANONYMOUS_ENABLED: "false"
  GF_LOG_MODE: "console"
  GF_LOG_LEVEL: "info"

# Grafana configuration
grafana.ini:
  server:
    domain: grafana.ecommerce.local
    root_url: "%(protocol)s://%(domain)s/"
    serve_from_sub_path: false
  security:
    allow_embedding: true
  users:
    allow_sign_up: false
    auto_assign_org_role: Viewer
  "auth.anonymous":
    enabled: false
  log:
    mode: console
    level: info

# Datasources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true

# RBAC
rbac:
  create: true

serviceAccount:
  create: true

# Security context
securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

# Image configuration
image:
  repository: grafana/grafana
  tag: "10.0.0"
  pullPolicy: IfNotPresent

# Sidecar configuration
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
    searchNamespace: monitoring
  datasources:
    enabled: true
    label: grafana_datasource

# Dashboard Providers
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'kubernetes-dashboards'
      orgId: 1
      folder: 'Kubernetes'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/kubernetes
    - name: 'monitoring-dashboards'
      orgId: 1
      folder: 'Monitoring'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/monitoring

# Pre-configured Dashboards from Grafana.com
dashboards:
  kubernetes:
    kubernetes-nodes:
      gnetId: 1860
      revision: 30
      datasource: Prometheus
    kubernetes-pods:
      gnetId: 6417
      revision: 1
      datasource: Prometheus
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    kubernetes-deployment:
      gnetId: 8588
      revision: 1
      datasource: Prometheus
    kubernetes-persistent-volumes:
      gnetId: 13646
      revision: 2
      datasource: Prometheus
    kubelet-metrics:
      gnetId: 2029
      revision: 2
      datasource: Prometheus
    etcd-metrics:
      gnetId: 3070
      revision: 2
      datasource: Prometheus
  monitoring:
    prometheus-stats:
      gnetId: 3662
      revision: 2
      datasource: Prometheus
    grafana-overview:
      gnetId: 179
      revision: 3
      datasource: Prometheus
