apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: darwinl06/user-service:latest
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8700
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "80m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411/"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
            - name: EUREKA_INSTANCE
              value: "user-service"
            
            - name: SPRING_APPLICATION_NAME
              value: "USER-SERVICE"
            - name: SERVER_PORT
              value: "8700"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/user-service"
          #   - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          #     value: "file:/etc/config/common-services.properties,file:/etc/config/user-service.properties"
          # volumeMounts:
          #   - name: config-volume
          #     mountPath: /etc/config
          livenessProbe:
            httpGet:
              path: /user-service/actuator/health
              port: 8700
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /user-service/actuator/health
              port: 8700
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
          - name: common-config-volume
            mountPath: /app/config
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config