
CREATE TABLE favourites (
	user_id INT(11) NOT NULL,
	product_id INT(11) NOT NULL,
	like_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (user_id, product_id, like_date)
);

