
CREATE TABLE payments (
  payment_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_id INT(11),
  is_payed BOOLEAN,
  payment_status VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

