
server:
  port: 8300

management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring:
#  datasource:
#    url: jdbc:mysql://host.docker.internal:3306/ecommerce_stage_db
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        use_sql_comments: true
#        format_sql: true

spring:
  datasource:
    url: jdbc:h2:mem:ecommerce_dev_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  file:
    name: src/main/resources/script/stage_log.log
    clean-history-on-start: true
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        data: DEBUG
      boot:
        autoconfigure:
          data:
            rest: DEBUG
            jpa: DEBUG
            orm: DEBUG

