apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: darwinl06/order-service:latest
        ports:
        - containerPort: 8300
        # resources:
        #   requests:
        #     memory: "384Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "384Mi"
        #     cpu: "250m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: EUREKA_INSTANCE
          value: "order-service"


          
        - name: SPRING_APPLICATION_NAME
          value: "ORDER-SERVICE"
        - name: SERVER_PORT
          value: "8300"
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: "/order-service"
        livenessProbe:
          httpGet:
            path: /order-service/actuator/health
            port: 8300
          initialDelaySeconds: 200
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /order-service/actuator/health
            port: 8300
          initialDelaySeconds: 200
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: common-config-volume
          mountPath: /app/config
      volumes:
      - name: common-config-volume
        configMap:
          name: common-config 