apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  labels:
    app: favourite-service
spec:
  type: ClusterIP
  ports:
  - port: 8800
    targetPort: 8800
    protocol: TCP
    name: http
  selector:
    app: favourite-service 