apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  labels:
    app: favourite-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8800"
spec:
  type: ClusterIP
  ports:
  - port: 8800
    targetPort: 8800
    protocol: TCP
    name: http
  selector:
    app: favourite-service 